spring:
  profiles:
    active: prod

  jackson:
    time-zone: Asia/Seoul

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  cloud:
    aws:
      parameterstore:
        enabled: false

jwt:
  secret:
    key: dGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9ySFMyNTY=

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
